module.exports = {
  extends: ["eslint:recommended"],

  rules: {
    "accessor-pairs": "warn",
    "array-callback-return": "warn",
    "arrow-body-style": ["warn", "as-needed"],
    "block-scoped-var": "warn",
    "class-methods-use-this": "warn",
    // "consistent-return": "off", // treated by typescript-eslint
    "consistent-this": "warn",
    "default-case-last": "warn",
    "default-case": "warn",
    // "default-param-last": "off", // treated by typescript-eslint
    "func-style": "warn",
    "generator-star-spacing": "warn",
    "grouped-accessor-pairs": "warn",
    "guard-for-in": "warn",
    "lines-between-class-members": "warn",
    "logical-assignment-operators": "warn",
    "no-alert": "warn",
    "no-array-constructor": "warn",
    "no-await-in-loop": "warn",
    "no-caller": "warn",
    "no-console": "warn",
    "no-constant-binary-expression": "warn",
    "no-constant-condition": ["warn", { checkLoops: false }],
    "no-constructor-return": "warn",
    "no-div-regex": "warn",
    "no-else-return": "warn",
    "no-empty-static-block": "warn",
    "no-eq-null": "warn",
    "no-eval": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-extra-label": "warn",
    "no-floating-decimal": "warn",
    "no-implicit-globals": "warn",
    "no-implied-eval": "warn",
    "no-invalid-this": "warn",
    "no-iterator": "warn",
    "no-label-var": "warn",
    "no-lone-blocks": "warn",
    "no-lonely-if": "warn",
    // "no-loop-func": "off",
    "no-multi-assign": "warn",
    "no-multi-str": "warn",
    "no-negated-condition": "warn",
    "no-new-func": "warn",
    "no-new-native-nonconstructor": "warn",
    "no-new-object": "warn",
    "no-new-wrappers": "warn",
    "no-new": "warn",
    "no-octal-escape": "warn",
    "no-param-reassign": "warn",
    "no-promise-executor-return": "warn",
    "no-proto": "warn",
    "no-return-assign": "warn",
    "no-return-await": "warn",
    "no-script-url": "warn",
    "no-self-compare": "warn",
    "no-sequences": "warn",
    "no-template-curly-in-string": "warn",
    "no-throw-literal": "warn",
    "no-underscore-dangle": "warn",
    "no-unmodified-loop-condition": "warn",
    "no-unneeded-ternary": "warn",
    "no-unreachable-loop": "warn",
    "no-unused-expressions": "warn",
    "no-unused-private-class-members": "warn",
    "no-unused-vars": "off",
    "no-useless-call": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-concat": "warn",
    "no-useless-rename": "warn",
    "no-useless-return": "warn",
    "no-var": "warn",
    "no-void": "off",
    "object-shorthand": "warn",
    "operator-assignment": "warn",
    "padding-line-between-statements": [
      "warn",
      {
        blankLine: "always",
        prev: "*",
        next: ["return", "class", "export"],
      },
      {
        blankLine: "always",
        prev: ["return", "class", "export"],
        next: "*",
      },
      { blankLine: "any", prev: "export", next: "export" },
      {
        blankLine: "always",
        prev: "*",
        next: ["block-like", "function"],
      },
      {
        blankLine: "always",
        prev: ["block-like", "function"],
        next: "*",
      },
      {
        blankLine: "any",
        prev: ["block-like", "function"],
        next: ["break", "continue"],
      },
      { blankLine: "always", prev: "*", next: ["case", "default"] },
      { blankLine: "any", prev: "case", next: "case" },
      { blankLine: "always", prev: "*", next: ["const", "let"] },
      { blankLine: "always", prev: ["const", "let"], next: "*" },
      { blankLine: "any", prev: ["const", "let"], next: ["const", "let"] },
    ],
    "prefer-arrow-callback": "warn",
    "prefer-const": "warn",
    "prefer-destructuring": "warn",
    "prefer-exponentiation-operator": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-object-has-own": "warn",
    "prefer-object-spread": "warn",
    "prefer-promise-reject-errors": "warn",
    "prefer-regex-literals": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "require-atomic-updates": "warn",
    "symbol-description": "warn",
    "yield-star-spacing": "warn",
    camelcase: "warn",
    curly: ["warn", "all"],
    eqeqeq: "warn",
    radix: "warn",
    strict: "warn",
    yoda: "warn",
  },

  overrides: [
    {
      files: "*.{js,ts}",
      rules: {
        "no-undef": "off",
      },
    },
  ],
};
