module.exports = {
  extends: ["plugin:react/recommended", "plugin:react/jsx-runtime"],

  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
  },

  settings: {
    react: {
      version: "detect",
    },
  },

  rules: {
    "react/boolean-prop-naming": [
      "warn",
      {
        rule: "^(is|has|was)[A-Z]([A-Za-z0-9]?)+",
        validateNested: true,
      },
    ],
    "react/button-has-type": "warn",
    "react/default-props-match-prop-types": "off",
    "react/destructuring-assignment": [
      "error",
      "always",
      {
        destructureInSignature: "always",
      },
    ],
    "react/display-name": "warn",
    // "react/forbid-component-props": "off",
    // "react/forbid-dom-props": "off",
    // "react/forbid-elements": "off",
    // "react/forbid-foreign-prop-types": "off",
    // "react/forbid-prop-types": "off",
    "react/function-component-definition": [
      "warn",
      {
        namedComponents: "arrow-function",
        unnamedComponents: "arrow-function",
      },
    ],
    "react/hook-use-state": "warn",
    "react/iframe-missing-sandbox": "warn",
    "react/jsx-boolean-value": "warn",
    // "react/jsx-child-element-spacing": "off/prettier",
    // "react/jsx-closing-bracket-location": "off/prettier",
    // "react/jsx-closing-tag-location": "off/prettier",
    "react/jsx-curly-brace-presence": ["warn", "never"],
    // "react/jsx-curly-newline": "off/prettier",
    // "react/jsx-curly-spacing": "off/prettier",
    // "react/jsx-equals-spacing": "off/prettier",
    "react/jsx-filename-extension": [
      "error",
      {
        allow: "as-needed",
        extensions: [".jsx", ".tsx"],
      },
    ],
    // "react/jsx-first-prop-new-line": "off/prettier",
    "react/jsx-fragments": "warn",
    "react/jsx-handler-names": [
      "warn",
      {
        checkLocalVariables: true,
      },
    ],
    // "react/jsx-indent-props": "off/prettier",
    // "react/jsx-indent": "off/prettier",
    "react/jsx-key": [
      "warn",
      {
        checkFragmentShorthand: true,
        checkKeyMustBeforeSpread: true,
        warnOnDuplicates: true,
      },
    ],
    "react/jsx-max-depth": [
      "warn",
      {
        max: 8,
      },
    ],
    // "react/jsx-max-props-per-line": "off/prettier",
    // "react/jsx-newline": "off/prettier",
    // "react/jsx-no-bind": "off",
    // "react/jsx-no-comment-textnodes": "off",
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-leaked-render": [
      "warn",
      {
        validStrategies: ["coerce", "ternary"],
      },
    ],
    // "react/jsx-no-literals": "off",
    "react/jsx-no-script-url": "warn",
    "react/jsx-no-target-blank": "warn",
    "react/jsx-no-undef": "error",
    "react/jsx-no-useless-fragment": "warn",
    // "react/jsx-one-expression-per-line": "off/prettier",
    "react/jsx-pascal-case": "error",
    // "react/jsx-props-no-multi-spaces": "off/prettier",
    // "react/jsx-props-no-spreading": "off",
    // "react/jsx-sort-props": "off",
    // "react/jsx-tag-spacing": "off/prettier",
    // "react/jsx-uses-react": "off",
    // "react/jsx-uses-vars": "off",
    // "react/jsx-wrap-multilines": "off/prettier",
    // "react/no-access-state-in-setstate": "off",
    // "react/no-adjacent-inline-elements": "off",
    "react/no-array-index-key": "error",
    // "react/no-arrow-function-lifecycle": "off",
    "react/no-children-prop": "error",
    "react/no-danger-with-children": "error",
    "react/no-danger": "error",
    "react/no-deprecated": "error",
    // "react/no-did-mount-set-state": "off",
    // "react/no-did-update-set-state": "off",
    // "react/no-direct-mutation-state": "off",
    // "react/no-find-dom-node": "off",
    "react/no-invalid-html-attribute": "warn",
    // "react/no-is-mounted": "off",
    "react/no-multi-comp": [
      "warn",
      {
        ignoreStateless: true,
      },
    ],
    "react/no-namespace": "warn",
    "react/no-object-type-as-default-prop": "warn",
    // "react/no-redundant-should-component-update": "off",
    // "react/no-render-return-value": "off",
    // "react/no-set-state": "off",
    // "react/no-string-refs": "off",
    "react/no-this-in-sfc": "error",
    // "react/no-typos": "off",
    "react/no-unescaped-entities": "warn",
    "react/no-unknown-property": "error",
    // "react/no-unsafe": "off",
    "react/no-unstable-nested-components": "warn",
    // "react/no-unused-class-component-methods": "off",
    // "react/no-unused-prop-types": "off",
    // "react/no-unused-state": "off",
    // "react/no-will-update-set-state": "off",
    "react/prefer-es6-class": ["warn", "always"],
    // "react/prefer-exact-props": "off",
    "react/prefer-read-only-props": "warn",
    "react/prefer-stateless-function": "warn",
    "react/prop-types": "warn",
    // "react/react-in-jsx-scope": "off",
    // "react/require-default-props": "off",
    // "react/require-optimization": "off",
    "react/require-render-return": "warn",
    "react/self-closing-comp": [
      "warn",
      {
        component: true,
        html: true,
      },
    ],
    // "react/sort-comp": "off",
    // "react/sort-default-props": "off",
    // "react/sort-prop-types": "off",
    // "react/state-in-constructor": "off",
    // "react/static-property-placement": "off",
    "react/style-prop-object": "warn",
    "react/void-dom-elements-no-children": "warn",
  },

  overrides: [
    {
      files: ["**/{page,layout,route}.{ts,tsx}"],
      rules: {
        "react/function-component-definition": "off",
      },
    },
  ],
};
